name: Bug Report
description: Report a bug in Planit
title: "fix: "
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please provide detailed information about the bug.

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Where is the bug occurring?
      options:
        - Backend
        - Frontend
        - DevOps
        - Documentation
        - Testing
        - Full Stack
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this bug?
      options:
        - 🔴 Critical (Blocker)
        - 🟠 High (Major issue)
        - 🟡 Medium (Moderate impact)
        - 🟢 Low (Minor issue)
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Size
      description: Estimated effort to fix
      options:
        - XS (1-2 hours)
        - S (2-4 hours)
        - M (1-2 days)
        - L (3-5 days)
        - XL (1+ week)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
      placeholder: What is happening?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System information
      placeholder: |
        - OS: [e.g., Ubuntu 22.04]
        - Browser: [e.g., Chrome 120]
        - Node version: [e.g., 20.x]
        - npm version: [e.g., 10.x]

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages or logs
      render: shell
