name: Feature Request
description: Propose a new feature for Planit
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please provide detailed information about the feature you'd like to see implemented.

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Which part of the application does this affect?
      options:
        - Backend
        - Frontend
        - DevOps
        - Documentation
        - Testing
        - Full Stack
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - 🔴 Critical
        - 🟠 High
        - 🟡 Medium
        - 🟢 Low
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Size
      description: Estimated effort required
      options:
        - XS (1-2 hours)
        - S (2-4 hours)
        - M (1-2 days)
        - L (3-5 days)
        - XL (1+ week)
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Type of work
      options:
        - Feature
        - Enhancement
        - Refactoring
        - Bug Fix
        - Documentation
        - Testing
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the feature
      placeholder: What should this feature do?
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Technical requirements and implementation details
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: Technical Notes
      description: Any technical details, dependencies, or considerations
      placeholder: Libraries, APIs, patterns to use

  - type: textarea
    id: related
    attributes:
      label: Related Issues
      description: Link to related issues or dependencies
      placeholder: |
        Depends on #123
        Related to #456
